ALTER TABLE products
  MODIFY COLUMN type_produit ENUM('MATIERE_PREMIERE','PRODUIT_FINI','CONSOMMABLE','NON_CONSOMMABLE','SERVICE') DEFAULT 'MATIERE_PREMIERE';

ALTER TABLE stocks
  ADD COLUMN IF NOT EXISTS seuil_minimum DECIMAL(15,2) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS etat ENUM('DISPONIBLE','EN_LAVAGE','USE','ENDOMMAGE','REBUT','PERDU') NOT NULL DEFAULT 'DISPONIBLE';

UPDATE stocks SET seuil_minimum = 5 WHERE seuil_minimum = 0;
