CREATE TABLE IF NOT EXISTS bar_equipments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(150) NOT NULL,
  categorie VARCHAR(100) NOT NULL DEFAULT 'Divers',
  description TEXT NULL,
  quantite INT UNSIGNED NOT NULL DEFAULT 1,
  etat ENUM('EN_SERVICE', 'A_REPARER', 'HORS_SERVICE') NOT NULL DEFAULT 'EN_SERVICE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_bar_equipments_categorie (categorie),
  KEY idx_bar_equipments_etat (etat)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;