CREATE TABLE IF NOT EXISTS maintenance_workers (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(100) NOT NULL,
  prenom VARCHAR(100) NULL,
  telephone VARCHAR(50) NULL,
  email VARCHAR(150) NULL,
  specialite VARCHAR(100) NULL,
  date_debut DATE NULL,
  date_fin DATE NULL,
  statut ENUM('ACTIF','INACTIF') NOT NULL DEFAULT 'ACTIF',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

ALTER TABLE room_maintenance
  MODIFY COLUMN room_id BIGINT UNSIGNED NULL,
  MODIFY COLUMN date_declaration DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS location VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS equipment_label VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS worker_id BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS execution_date DATE NULL,
  ADD COLUMN IF NOT EXISTS finish_date DATE NULL,
  ADD COLUMN IF NOT EXISTS materials_cost BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS labor_cost BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_cost BIGINT NOT NULL DEFAULT 0;

ALTER TABLE room_maintenance
  MODIFY COLUMN type_intervention VARCHAR(30) NOT NULL;
UPDATE room_maintenance
SET type_intervention = CASE type_intervention
  WHEN 'PREVENTIVE' THEN 'AUTRE'
  WHEN 'CORRECTIVE' THEN 'AUTRE'
  WHEN 'URGENCE' THEN 'AUTRE'
  ELSE type_intervention
END;
ALTER TABLE room_maintenance
  MODIFY COLUMN type_intervention ENUM('PLOMBERIE','ELECTRICITE','MACONNERIE','CLIMATISATION','AUTRE') NOT NULL;
