CREATE TABLE IF NOT EXISTS casino_players (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  nom VARCHAR(150) NOT NULL,
  prenom VARCHAR(150) NULL,
  surnom VARCHAR(150) NULL,
  telephone VARCHAR(50) NULL,
  whatsapp VARCHAR(50) NULL,
  email VARCHAR(190) NULL,
  depot DECIMAL(15,2) NOT NULL DEFAULT 0,
  credit DECIMAL(15,2) NOT NULL DEFAULT 0,
  mode_jeu VARCHAR(100) NULL,
  statut ENUM('ACTIF', 'INACTIF') NOT NULL DEFAULT 'ACTIF',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_casino_players_name (nom, prenom),
  INDEX idx_casino_players_status (statut)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;